### PR TITLE
Users should be able to override the token when using the Slack compliance fix

### PR DESCRIPTION
**Pull request by singingwolfboy**

### CODE REVIEW

**Comment by Lukasa** [comment]
This looks reasonable to me.

**Comment by sigmavirus24** [comment]
Looks reasonable to me as well!

**Comment by singingwolfboy** [comment]
Any idea why Travis CI doesn't seem to be running the tests? It should have run them by now...

**Comment by Lukasa** [comment]
@singingwolfboy It is, but Travis just isn't putting tokens into GitHub for some reason: https://travis-ci.org/requests/requests-oauthlib/pull_requests

**Comment by singingwolfboy** [comment]
Ah, OK. Well, if the tests have run and passed, is there anything else that would prevent this from getting merged?

**Comment by sigmavirus24** [comment]
I'm figuring out why that's a problem now. Going to close/reopen this to see if that'll get Travis to report now.

**Comment by sigmavirus24** [comment]
There we go!

**Comment by sigmavirus24** [comment]
Merging!

**Pull request merged**
