### PR TITLE
Update google.rst

### PR DESCRIPTION
**Pull request by mrwangjianhui**
https://developers.google.com/identity/protocols/oauth2/openid-connect?hl=en#scope-param
https://developers.google.com/identity/protocols/oauth2/scopes#oauth2

### CODE REVIEW

**Review by JonathanHuot — APPROVED** [review]
LGTM

**Review by jtroussard — CHANGES_REQUESTED** [review]
With regards to making updates to the example files, can we introduce a new contribution requirement to include some sort of verification?

**Comment by mrwangjianhui** [comment]
Do i need to do anything else

**Comment by mrwangjianhui** [comment]
> > Do i need to do anything else
> 
> Is there a way to verify these changes work? Screen shot, demo, or something else maybe?

Without "openid", the "email" attribute is not returned:
{'id': '102430716320508450299', 'name': '王健辉', 'given_name': '健辉', 'family_name': '王', 'picture': 'https://lh3.googleusercontent.com/a-/AOh14GgIPx4ZiXyy-rEPCQu9ARptOQmXar2qwh1RIcqy=s96-c', 'locale': 'zh-CN'}
After adding "openid", the "email" attribute will be returned:
{'id': '102430716320508450299', 'email': 'mr.wangjianhui@gmail.com', 'verified_email': True, 'name': '王健辉', 'given_name': '健辉', 'family_name': '王', 'picture': 'https://lh3.googleusercontent.com/a-/AOh14GgIPx4ZiXyy-rEPCQu9ARptOQmXar2qwh1RIcqy=s96-c', 'locale': 'zh-CN'}

**Comment by jtroussard** [comment]
> > > Do i need to do anything else
> > 
> > 
> > Is there a way to verify these changes work? Screen shot, demo, or something else maybe?
> 
> Without "openid", the "email" attribute is not returned: {'id': '102430716320508450299', 'name': '王健辉', 'given_name': '健辉', 'family_name': '王', 'picture': 'https://lh3.googleusercontent.com/a-/AOh14GgIPx4ZiXyy-rEPCQu9ARptOQmXar2qwh1RIcqy=s96-c', 'locale': 'zh-CN'} After adding "openid", the "email" attribute will be returned: {'id': '102430716320508450299', 'email': '[mr.wangjianhui@gmail.com](mailto:mr.wangjianhui@gmail.com)', 'verified_email': True, 'name': '王健辉', 'given_name': '健辉', 'family_name': '王', 'picture': 'https://lh3.googleusercontent.com/a-/AOh14GgIPx4ZiXyy-rEPCQu9ARptOQmXar2qwh1RIcqy=s96-c', 'locale': 'zh-CN'}

was the example broken before?

**Review by jtroussard — APPROVED** [review]

**Comment by jtroussard** [comment]
Was able to verify this updates results in successfully implementation of the library, making small non-functional change to trigger new pipeline checks.

**Review by jtroussard — APPROVED** [review]
lgtm

**Pull request merged**
