### PR TITLE
WIP: Fix Travis Pipeline

### PR DESCRIPTION
**Pull request by JonathanHuot**
TODO list:
- fix travis
- fix coveralls
- autorelease when tagging

### CODE REVIEW

**Comment by JonathanHuot** [comment]
Hi @nateprewitt , can you go to https://app.travis-ci.com/organizations/requests/repositories and enable WebApp for requests-oauthlib please ?
It is required to restore TravisCI since the migration from org to com.
Note that mid/long term, a migration to GH Actions can be done.

**Comment by JonathanHuot** [comment]
Hi @nateprewitt again, we also need to add coveralls repository, perhaps here https://coveralls.io/repos/new . I have requested access from requests community, but I'm not sure it is the right way.. wondering how it was working before.
Any comments will be much appreciated.
Thanks

**Comment by nateprewitt** [comment]
Hi @JonathanHuot ,

I've authorized Travis CI although it's prompting for CC information to use their free trial. It _appears_ it may be working, but if not, we'll need to look into moving to Github Actions sooner than later.

In regards to Coveralls, I checked the repo and it says it's already activated. It shows as approved at the org level as well. If it's not working currently, adding codecov is relatively straight forward with actions as well.

```yml
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          name: "${{ runner.os }} (${{ matrix.python-version }})"
          files: ./coverage.xml
          verbose: true
```

**Comment by jtroussard** [comment]
Should we close this PR without merging?

**Comment by JonathanHuot** [comment]
Closed in favor of https://github.com/requests/requests-oauthlib/pull/470

**Pull request closed without merging**
