### PR TITLE
Adds client certificate parameter to OAuth2Session

### PR DESCRIPTION
**Pull request by amackera**
This allows users to specify a client certificate to pass to `requests`. This is useful for some OAuth providers that require client certificate authentication.

### CODE REVIEW

**Comment by amackera** [comment]
Related issue: https://github.com/requests/requests-oauthlib/issues/292

**Comment by Lukasa** [comment]
Requests should do this automatically: did you actually try using the `cert` argument in this way?

**Comment by sserrata** [comment]
Has anyone validated this behavior? I've tried including a client certificate a number of ways and keep seeing the following error message from my IdP:

`(invalid_client) <client-id> is configured to use client certificates but there were no client certificates sent in the request.`

Oauth2Session doesn't accept the `cert` argument. Attempting to pass it results in the following exception: 

`TypeError: __init__() got an unexpected keyword argument 'cert'`

The fetch_token method does accept the `cert` argument and the prepared fetch token body and request body appear to include it. Despite this, I'm still getting a 401 with the message mentioned above.

**Comment by amackera** [comment]
Hi @Lukasa yes, we tried using the `cert` argument, but it did not work. It's been a while since I looked at this issue though so my memory could be faulty! 

Feel free to close this PR if y'all know for a fact that `requests-oauthlib` supports client certificates out of the box.

**Comment by ltamaster** [comment]
I had the same problem, I tried to use the `cert`argument without luck.
Any advice on how to pass the certificate?

Thanks
Luis

**Comment by sserrata** [comment]
I've confirmed that the `cert` parameter works as either a `kwarg`, e.g. `fetch_token(cert='cert.pem')` or as an OAuth2Session() attribute, e.g. `oauth2session.cert = 'cert.pem'`.

**Comment by ltamaster** [comment]
I tried `oauth2session.cert =tmp-cert-path`  and oauth2session.refresh_token(****, cert=tmp-cert-path) without luck, any ideas? 
the certificate works ok on other calls (i am working with kubernetes sdk)

**Comment by calcium** [comment]
I just cloned the current trunk (master) and looking at the code for fetch_token
oauth2_session.py:219
       if method.upper() == 'POST':
            r = self.post(token_url, data=dict(urldecode(body)),
                timeout=timeout, headers=headers, auth=auth,
                verify=verify, proxies=proxies)

I dont see how this would work as is without the extra cert args. 

Yes, I need to do this too :-)

**Comment by Anmol-Porwal18** [comment]
Hi, Is using oauth2session.cert the expected way to pass certificates ?

I need this functionality too (to be able to pass certificate in fetch_token - which will take care of passing it further). Are we expecting this to be merged soon ?

**Comment by amackera** [comment]
Closing this (years old) PR due to lack of activity.

**Pull request closed without merging**
