### PR TITLE
Release 1.3.1

### PR DESCRIPTION
**Pull request by JonathanHuot**
After this MR is OK, we can tag the git commit, and it should (hopefully) automatically push the python package to pypi.
Have a look on changelog & new pipeline.

### CODE REVIEW

**Comment by JonathanHuot** [comment]
Note that I avoided adding the automatic Github Release publishing, as I have too many Github Actions related to this... I was not able to choose, as none of them seems complete!

Basically, I was trying to replace the lovely TravisCI "releases" provider:

```
deploy:
  - provider: releases
    api_key:
      secure: "<..>"
    on:
      tags: true
      all_branches: true
      condition: $TOXENV = py36
      repo: requests/requests-oauthlib

```

**Comment by JonathanHuot** [comment]
Pushing tag triggered the release in pypi as expected ! 
https://pypi.org/project/requests-oauthlib/1.3.1/

**Comment by jtroussard** [comment]
I think we need to rethink our code coverage check, there is a bug I think on coverall side that causing these -0% coverage changes and creates these merge blocks. These are a few options:

- workaround this and increase request-oauthlib coverall threshold to something like 0.01%
- don't check all versions of python for coverage - should only really check for maintained and/or supported versions (this could still leave us with a version that is returning the -0% change)
- Only run coverage against the latest version of python

https://github.com/lemurheavy/coveralls-public/issues/1608#issuecomment-1005177210

@JonathanHuot

**Comment by jtroussard** [comment]
@JonathanHuot - Circling back to this one here. Just needs a nudge to get it across the finish line. Who has access to the coveralls settings? Can we bump the coverage check threshold to 0.01% and run the pipeline against this release again?

**Comment by JonathanHuot** [comment]
thanks to @nateprewitt, the coverage threshold has been changed to 1%, and now all checks are passing!

@jtroussard, the story about restoring pipeline is done finally. Now we can focus on bug & features PR reviews..

**Pull request merged**
