### PR TITLE
Use requests-mock library, add tests for Slack compliance fix

### PR DESCRIPTION
**Pull request by singingwolfboy**
The tests are clearer and more accurate if we use the [requests-mock](https://github.com/openstack/requests-mock) library for mocking responses from requests. This pull request also adds a test for the Slack compliance fix.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
If we're going to hand write response data, I'd rather we use requests-mock. It's maintained and raises errors that are not "ConnectionError" when a request changes. responses is a poor excuse for a mocking library for requests.

Also, I'd rather we not mock any response bodies by hand, but that's a different arguement entirely.

**Comment by singingwolfboy** [comment]
@sigmavirus24 I had no idea that responses was not maintained, and that requests-mock was the library to use instead. I've updated my pull request. Does it look good?

**Comment by sigmavirus24** [comment]
:+1: from me.

**Comment by Lukasa** [comment]
:+1: from me too.

**Comment by singingwolfboy** [comment]
:dancers:

**Pull request merged**
