### PR TITLE
Fix `oauth_callback` change error

### PR DESCRIPTION
**Pull request by qnub**
Got error `request() got an unexpected keyword argument 'oauth_callback'` when try to call `.fetch_request_token(url=self.request_token_url, oauth_callback=self.redirect_uri)`

### CODE REVIEW

**Comment by Lukasa** [comment]
This change is definitely not right. `oauth_callback` is not a parameter we accept anywhere. What are you trying to achieve?

**Comment by qnub** [comment]
@Lukasa sad, because is only way to force twitter to direct user back to URL other than set on apps.twitter.com.

Check «Step 1» here https://dev.twitter.com/web/sign-in/implementing:

> The only unique parameter in this request is `oauth_callback`, which must be a URL-encoded version of the URL you wish your user to be redirected to when they complete step 2.

**Comment by Lukasa** [comment]
If you want to set a parameter, you should use `params=` instead. =)

**Comment by qnub** [comment]
Have you tryed to do that? Seems it's not work.

**Comment by Lukasa** [comment]
When you say it doesn't work, what specifically do you mean? Additionally, have you tried setting `data=` instead of `params=`?

**Pull request closed without merging**
