### PR TITLE
add option to pass `params` in POST request

### PR DESCRIPTION
**Pull request by AdamGold**
- [x] add tests

### CODE REVIEW

**Comment by singingwolfboy** [comment]
It looks like there's a lot of changes in this commit that are just about reformatting code. Can you put those in a separate commit, or even better, a separate pull request? That will make it easier to review this, as well as easier to look through the Git history to find out how this project changed over time.

**Comment by AdamGold** [comment]
@singingwolfboy Absolutely! My bad. All done.

**Comment by singingwolfboy** [comment]
This pull request is still full of formatting changes. I've tried to pull the actual code changes out into a separate pull request: #369. Could you please review that, and tell me if it solves your problem?

**Comment by AdamGold** [comment]
Looking at the changes there are really only 2 formatting changes I can spot. There are some lines that it looks like a formatting change but it's actually a parameter addition or something. Anyways, I'll take a look at your PR! :)

**Comment by singingwolfboy** [comment]
> There are some lines that it looks like a formatting change but it's actually a parameter addition or something.

Yes, this is _precisely_ the reason I asked you to separate the formatting changes from the code changes. When you mix the two, it becomes harder to understand what is being changed, and why.

I merged #368 to make this easier in the future.

**Pull request closed without merging**
