### PR TITLE
add 'use_auto_state' parameter for 'authorization_url' method

### PR DESCRIPTION
**Pull request by MilovanovM**
'state' is an optional parameter for OAuth2

### CODE REVIEW

**Comment by Lukasa** [comment]
So, while it's optional...do you really have to remove it? It's extremely important, and removing it exposes web services to CSRF attacks.

**Comment by MilovanovM** [comment]
I completely agree, it's important, but I think it should be set by dev, not by library itself. The library should be flexible for all needs.
However, all old (and new) code will work as it did before because `use_auto_state` is `True` by default

**Comment by Lukasa** [comment]
I guess what I'm trying to ask is: is there ever a sensible use-case where you'd want the state removed?

**Comment by MilovanovM** [comment]
There is a specific use-case in our app. I think we could bypass it in another way.
Thanks, closing the PR out

**Pull request closed without merging**
