### PR TITLE
Update google.rst

### PR DESCRIPTION
**Pull request by steven1227**
The url for token and authorization misplaced.

### CODE REVIEW

**Comment by steven1227** [comment]
The URL for Google Oauth Authenticate and Google Oauth Token should swap into right place.

**Comment by Lukasa** [comment]
Thanks! :sparkles:

**Comment by steven1227** [comment]
@Lukasa Can I ask that is any way to revoke the token in this library?

**Comment by Lukasa** [comment]
Not using this library, no.

**Pull request merged**
